export const ON_CHANGE_SIGNUSERNAME = 'ON_CHANGE_SINGUSERNAME';
export const ON_CHANGE_SIGNPASSWORD = 'ON_CHANGE_SIGNPASSWORD';
export const ON_CHANGE_COMFIRMPWD = 'ON_CHANGE_COMFIRMPWD';
export const SET_STATUS = 'SET_STATUS';
export const UPDATE_MSG = 'UPDATE_MSG';